apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-ace
  labels:
    app: ibm-ace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibm-ace
  template:
    metadata:
      labels:
        app: ibm-ace
    spec:
      containers:
      - name: ibm-ace
        image: preciousokpor/ibm-barfiles-image:20241119164301
        ports:
        - containerPort: 7600  # ACE Web UI and HTTP listener
        - containerPort: 7800  # Additional port as per documentation
        - containerPort: 7843  # Additional port as per documentation
        env:
        - name: LICENSE
          value: accept
        - name: ACE_SERVER_NAME
          value: ACESERVER
        - name: ACE_WORKING_DIR
          value: "/home/aceuser/ace-server" # Adjusted according to documentation
        # Uncomment the following lines to enable metrics
        #- name: ACE_ENABLE_METRICS
        #  value: "true"
        #- containerPort: 9483  # Port for Prometheus metrics
        # Uncomment the following lines if you have initial configuration files
        #volumeMounts:
        #- name: initial-config
        #  mountPath: /home/aceuser/initial-config
      # Uncomment the following lines if you have initial configuration files
      #volumes:
      #- name: initial-config
      #  configMap:
      #    name: ace-initial-config  # Replace with your ConfigMap name if using ConfigMap
